### PR TITLE
Clean up in preparation for docs

### PR DESCRIPTION
**Pull request by paulathevalley**
- Rename "Custom Theme" example to "Custom Styles" so as not to confuse it with victory-wide theming support 
- Move other examples to `src/` but keep demo working as is

### CODE REVIEW

**Comment by boygirl** [comment]
@paulathevalley LGTM except I havent been able to get this part to work for me `const appHistory = useScroll(useRouterHistory(createBrowserHistory))();`

**Comment by boygirl** [comment]
Also, I want to update to latest Victory and add an example before you publish. You're not planning on publishing tonight are you? If you are, the example I want to add is here. The example is in this branch https://github.com/FormidableLabs/victory-examples/tree/tooltip-example. Otherwise I'll match that branch to these changes over the weekend and write the promised copy to go along with these examples

**Comment by paulathevalley** [comment]
I did want to update `victory-examples` so that `victory-docs` can pull in the docs component and put it up on the site with the new victory release. However, I can wait to publish until you've merged that example!

**Pull request merged**
