### PR TITLE
Candlestick example

### PR DESCRIPTION
**Pull request by ebrillhart**
fulfilling #30 

this has the upper/lower bounds area component, a bar component, and interactivity to switch between three data sets. candlestick component hasn't been released in victory yet - I'll add once it's been included in a release and victory has been updated. I'll also make the overall chart a little prettier and try to add some shared events

@boygirl

### CODE REVIEW

**Comment by ebrillhart** [comment]
@boygirl does this look good to go as long as candlestick is added well?

**Comment by boygirl** [comment]
Yeah, this will look awesome once you get candlestick in.

**Comment by boygirl** [comment]
@ebrillhart some feedback
It's really unclear what the area chart corresponds to in the data
the green is a little abrasive
can you adjust the domain so that the bars stay inside the axis, and the candlesticks have a little padding inside the area?

**Comment by ebrillhart** [comment]
@boygirl thanks, I'll make those changes. Re: buttons - each bar and candlestick is supposed to represent a period of time equal to what's on the button. which is working for me, but maybe is not for you.

**Comment by boygirl** [comment]
The buttons are working, the relationship just wasn't clear. I thought those were supposed to represent the total span of time. It's confusing to have them represent the time / candle when you also have the total domain changing when the buttons are clicked.

**Comment by ebrillhart** [comment]
@boygirl yeah, I can see that, it made sense to me, but that's probably because that's the way the example I was basing it off of had it. What is the best way to clarify that?

**Comment by boygirl** [comment]
@ebrillhart either that, or have the span of time always stay the same, and just have the bars / candlesticks get more dense

**Comment by boygirl** [comment]
@ebrillhart a bit of a problem when resizing: 
screen shot 2016-08-03 at 3 35 52 pm

and the density of data in the quarterly section is a little much. Other than that, good to go.

**Pull request merged**
